# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_produucto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('lugar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=140)),
                ('genero', models.CharField(choices=[('terror', 'Terror'), ('SciFi', 'Ciencia Ficción')], max_length=50)),
                ('titulo', models.CharField(max_length=20)),
                ('sinopsis', models.TextField()),
                ('cienes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='main.Cine')),
            ],
        ),
        migrations.AlterField(
            model_name='produucto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to=settings.AUTH_USER_MODEL),
        ),
    ]
